name: summary CI
on:
  repository_dispatch:
    types: [summary]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: upptime/uptime-monitor@master
        with:
          command: "summary"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
